apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-sb-app
  janus-idp.io/tekton: test-sb-app
  backstage.io/kubernetes-id: test-sb-app
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: test-sb-app
resources: 
- deployment.yaml
- route.yaml
- service.yaml
